### ISSUE TITLE
Regarding the lack of maintenance

### ISSUE THREAD

**Issue by 0paIescent** [GoldenOwlAsia/react-native-twitter-signin#100]
This issue is mainly directed towards GoldenOwlAsia @thethanghn, but also to any other major contributors.

There are multiple issues with this project that have been brought up through both Issues and Pull Requests. GoldenOwlAsia has only responded to two currently open issues, once on July 4th, 2017 and to another on June 9th, 2018. GoldenOwlAsia has not responded to any of the open Pull Requests. The latest merge was on December 25, 2017,  over six months ago. It is obvious that this project is no longer being maintained.

This is a formal request to request access to commit code to this project, or for you to address the lack of maintenance. If you do not allow access and continue to not maintain the project, then I will make a full fork (create a new project, copy the code over under a new name, mainly because I will not be interested in pushing merges upstream if there will be no support here).

I will give credit to the code you and the other contributors have added to this project of course, and I will also link this project so people interested in the original can see it.

If there is no response in one week from today, then I will assume that this project is abandoned and will go through with making my own full fork.

**Comment by juanlet** [comment]
+1 to this

**Comment by stokesbga** [comment]
lol

**Comment by 0paIescent** [comment]
@juanlet Thanks, that sounds great, I'd love it if you'd like to contribute. It looks like you're really knowledgeable in Swift/Objective-C, where I'm much more confident in Java. The more people with the more skills the better.

**Comment by thethanghn** [comment]
hey I am back
