### ISSUE TITLE
...tried to require 'react-native', but there are several files providing this module

### ISSUE THREAD

**Issue by Quanda** [GoldenOwlAsia/react-native-twitter-signin#116]
The error refers to ../node_modules/react-native-twitter-signin/node_modules/react-native/package.json as the source of the issue

I believe the problem is the react-native-twitter-signin package.json is listing react-native as a dependency, but it should rather be a peerDependency. Not sure on this, but it's a hunch.

My app is able to build successfully, but it crashes on load

![screen shot 2018-09-14 at 4 56 48 pm](https://user-images.githubusercontent.com/4842748/45574895-74649780-b83f-11e8-9115-f1dd0afad5a7.png)

Anyone else have this problem?

**Comment by deflorilemarului** [comment]
still have this issue: "tries to require `react-native`, but there are several files providing this module. You can delete or fix them: "

because of that, this extension cannot be used for IOS.

**Comment by ajaykumar97** [comment]
Try deleting ``react-native`` folder from the `node_modules/react-native-twitter-signin/node_modules` folder.
