### ISSUE TITLE
[Question] Logging Out Functionality?

### ISSUE THREAD

**Issue by StephenMayeux** [GoldenOwlAsia/react-native-twitter-signin#13]
Hey @GoldenOwlAsia great repo, and it worked as expected on the first try! 

I was wondering if it was possible to log a user out? I was able to successfully log in once, but I would like to log out so that another Twitter user could log in. 

Is there any way to achieve this right now? I'm not an expert at Objective C, but I could only find one logIn method available to me. 

Please let me know what you think, and thanks again!

**Comment by thethanghn** [comment]
@StephenMayeux it is possible to log user out, you can implement the bridged functions to do that. I think it should be pretty straightforward.

**Comment by StephenMayeux** [comment]
Thanks for responding, @thethanghn. I don't know what you mean by **the bridged functions** or how to implement that. Is this something that I could do in JavaScript, or would I have to edit some Objective C files? Please let me know and thanks!

**Comment by thethanghn** [comment]
it is wrapper function that you have to write in both iOS and Java code to give interface for JavaScript to call to.

**Comment by StephenMayeux** [comment]
Thank you. I decided to take a different approach.
