### ISSUE TITLE
Error: Failed to get request token

### ISSUE THREAD

**Issue by abdi4** [GoldenOwlAsia/react-native-twitter-signin#152]
Ive been stuck on this for about 3 days now. I followed the instructions exactly like the docs. Added the callback url and all the other solutions on the internet. This error is on Android but ios doesn't do anything when i click the button.  Also shows no errors or warning when debugging. Please help.
![Screenshot_1583994292](https://user-images.githubusercontent.com/43745412/76493456-8f12cf00-642a-11ea-8a84-e5c4e075d56d.png)

**Comment by yash-atreya** [comment]
Hey @abdi4 did you solve this? If yes, then can you please tell me how??

**Comment by abdi4** [comment]
for me it was caused because i didnt set callback url

**Comment by kamalkishor8878** [comment]
1. I am also facing the same issue.
2. i have already added the android and ios callbacks but still is is not working.
3. It returning the issue (Failed to get request token)
