### ISSUE TITLE
Authentication simply stopped working in both ios and android

### ISSUE THREAD

**Issue by abdi4** [GoldenOwlAsia/react-native-twitter-signin#155]
Did something change recently because a few days ago everything was working fine and all of a sudden i can't authenticate using twitter

**Comment by lesmo** [comment]
What do you mean _"all of the sudden"_? I just checked this on a currently published app (published on January) and is working as expected. Also, the specific commit the published App is using is 5241060d7079c2bc8fda7202f33ace80a507ab28 - not sure if `npm` is different by now.
