### ISSUE TITLE
i could not follow the whole dependecies

### ISSUE THREAD

**Issue by CusProjects** [GoldenOwlAsia/react-native-twitter-signin#16]
extends SocialButton // Is undefined
Constants.TWITTER_COMSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET // is undefined

or can i create a class extending from React.Component? 

or please give un full example...

**Comment by oureta** [comment]
The sample code is just to show how `NativeModules` should be imported. Don't copy the whole sample code. You also need to replace `Constants.TWITTER_CONSUMER_` keys.

**Comment by mobilemaster5** [comment]
I got an error:
`cannot find variable: SocialButton`

I have added the socialbutton using:
- `npm install react-social-button --save`
- `var SocialButton = require('react-social-button');`

from: https://devhub.io/zh/repos/AljoschaMeyer-react-social-button
But it's not working
Could you please give the solution about that ?
