### ISSUE TITLE
Support for React Native v0.40

### ISSUE THREAD

**Issue by oureta** [GoldenOwlAsia/react-native-twitter-signin#17]
On RN v0.40, iOS native headers have been moved. Imports of RN Headers should be changed from:

`#import "RCTBridge.h"`

to

`#import <React/RCTBridge.h>`

**Comment by justinobney** [comment]
https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.p714l4p8r
