### ISSUE TITLE
TwitterShareExtensionUIResources.bundle'. Couldn't follow symbolic link.

### ISSUE THREAD

**Issue by mirzahayat** [GoldenOwlAsia/react-native-twitter-signin#171]
Hi I'm facing this error when i'm build the release apk file, by adding dependency in Package.jason file
"react-native-twitter-signin": "github:GoldenOwlAsia/react-native-twitter-signin#master",

Error:
node_modules/react-native-twitter-signin/ios/dependencies/TwitterShareExtensionUIResources.bundle'. Couldn't follow symbolic link.

Any one help me,How i can resolve it,

**Comment by MaxABInBev** [comment]
@mirzahayat were you able to find any solution for that ?

**Comment by umartryngo** [comment]
No i did not find any solution,

**Comment by mirzahayat** [comment]
No i did not find any solutions

**Comment by mirzahayat** [comment]
@MaxABInBev  i have forked the library with some little bit changing kindly use this link
 https://github.com/mirzahayat/react-native-twitter-signin.git
 hope so it will help you,
 Two files are missing 
 1: TwitterKitResources.bundle
2: TwitterShareExtensionUIResources.bundle
i have resolve it by adding these two files in node_modules/react-native-twitter-signin/ios/dependencies
