### ISSUE TITLE
Fabric called multiple times

### ISSUE THREAD

**Issue by Grundmanis** [GoldenOwlAsia/react-native-twitter-signin#19]
Nothing happens when i try to login, except the message below in log:
`[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize`

Earlier everything worked perfectly, but then i had an error in other package and while i was fighting it, i have made `npm update` , `react-native link` and also included Pod system

Googling doesn't helped, it seems i'm the first with this error

**Comment by parkerproject** [comment]
You should call multiple Fabric like this `[Fabric with:@[[Crashlytics class], [RNBranch class]]];`
