### ISSUE TITLE
Apple store reject UIWebView

### ISSUE THREAD

**Issue by Nicat26** [GoldenOwlAsia/react-native-twitter-signin#195]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "AppName" AppVersion. Please correct the following issues, then upload again.ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

**Comment by mitalsmitv** [comment]
How to resolve these issue ? i am facing these since 1 month.
