### ISSUE TITLE
Java linker issue

### ISSUE THREAD

**Issue by GeoffreyPlitt** [GoldenOwlAsia/react-native-twitter-signin#2]
Followed all your instructions, and I've integrated with lots of other RN modules.

A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.twitter.sdk.android:twitter:1.13.1.
>      Searched in the following locations:
>          file:/Users/webfreelance10/nerdhq/node_modules/react-native/android/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.pom
>          file:/Users/webfreelance10/nerdhq/node_modules/react-native/android/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.aar
>          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.pom
>          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.aar
>          file:/usr/local/opt/android-sdk/extras/google/m2repository/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.pom
>          file:/usr/local/opt/android-sdk/extras/google/m2repository/com/twitter/sdk/android/twitter/1.13.1/twitter-1.13.1.aar
>      Required by:
>          EAPlay:app:unspecified > EAPlay:react-native-twitter-signin:unspecified

**Comment by rameshvishnoi90904** [comment]
Facing Same issue

**Comment by jitu9717** [comment]
@GeoffreyPlitt @rameshvishnoi90904 : just put this 
repositories {
  maven { url 'https://maven.fabric.io/public' }
}

just above the dependencies in build.gradle inside the app folder
