### ISSUE TITLE
No visible @interface for 'Twitter' declares the selector 'logInWithMethods::'

### ISSUE THREAD

**Issue by DannyAziz** [GoldenOwlAsia/react-native-twitter-signin#28]
When building I get this error: 
`No visible @interface for 'Twitter' declares the selector 'logInWithMethods::'`

I'm using RN 0.4 and Twitter Kit 3.0.3

**Comment by brayan9413** [comment]
With that version of twitter kit I had that problem, now I am using these versions and runs without problem
   - Fabric (1.6.11)
   - TwitterCore (2.8.0):
   - TwitterKit (2.8.1):

**Comment by thethanghn** [comment]
it was updated to use TwitterKit 3.0, so this should work fine now
