### ISSUE TITLE
Not used default twitter app loggedIn account in ios

### ISSUE THREAD

**Issue by bhoomika911** [GoldenOwlAsia/react-native-twitter-signin#29]
Hi...

This is great package for login with twitter for react native.It is working good.But I have one issue.

Twitter app is installed in my ios device and i logged in with my twitter account in twitter app.After that when I tried to login with twitter using this package in my react native app,it does not use that twitter account and opening login screen.

By default ,it has to use default logged in twitter account of Twitter app just like facebook provides.

**Comment by bhoomika911** [comment]
Any one can help?

**Comment by Nits7029** [comment]
+1

**Comment by thethanghn** [comment]
I believe the new version would fix this issue for you @bhoomika911
