### ISSUE TITLE
npm install react-native-twitter-signin --save gives error

### ISSUE THREAD

**Issue by bbeckk** [GoldenOwlAsia/react-native-twitter-signin#48]
npm WARN react-native-twitter-signin@1.0.2 requires a peer of react@15.4.2 but none was installed.
npm WARN react-native-twitter-signin@1.0.2 requires a peer of react-native@0.42.3 but none was installed.

**Comment by bbeckk** [comment]
updating npm solved this problem.

**Comment by thethanghn** [comment]
fixed
