### ISSUE TITLE
how do I properly link iOS files?

### ISSUE THREAD

**Issue by faceyspacey** [GoldenOwlAsia/react-native-twitter-signin#5]
I'm getting this error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TWTRAPIClient", referenced from:
      objc-class-ref in TwitterSignin-DD11A2C65187B8A2.o
  "_OBJC_CLASS_$_Twitter", referenced from:
      objc-class-ref in TwitterSignin-DD11A2C65187B8A2.o
      objc-class-ref in AppDelegate.o
     (maybe you meant: _OBJC_CLASS_$_TwitterSignin)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I'm used to adding .xcodeproj libraries, but not individual files like this. What I've done is I added the *TwitterKit* fabric library (something not mentioned in the documentation) and overcame some initial errors, but now I'm getting the above issue, which seems to have to do with linking the binaries, compile sources etc. I added Twitter.framework to `Link Binary With Libaries` and now I've tried adding `Twitter.Signin.m/h` to the Compile sources, but no luck.

What am I missing?

**Comment by faceyspacey** [comment]
ok, i found the issue. in my particular case, cocoa pods wasn't set up correctly, and I had to add `$(inherited)` to my other linker flags in build settings as per:

http://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods

**Comment by punksta** [comment]
@faceyspacey hey, I am having exact same issue. `$(inherited)` didn't help. Have you made anything else?
