### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by SambitPrakash** [GoldenOwlAsia/react-native-twitter-signin#50]
Hello @GoldenowlConsultingCompany , thanks for the tutorial.
I have one issue. I went through the tutorial and followed all the instruction.

const { RNTwitterSignIn } = NativeModules;
const Constants = {
    TWITTER_CONSUMER_KEY: '<Some consumer Key>',
    TWITTER_CONSUMER_SECRET: '<Some consumer secret>',
};

RNTwitterSignIn.init(Constants.TWITTER_CONSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET);
While initializing RNTwitterSignIn with TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET, app got crash. It says 

<B> Cannot read property 'init' of undefined </B>

Please check the below screen shot. Please let me know where i am going wrong. 
Thanks

![simulator screen shot 05-aug-2017 7 30 48 pm](https://user-images.githubusercontent.com/22074730/28995992-a69eda9a-7a14-11e7-890d-591c9f54a28b.png)

**Comment by HideyaSwider** [comment]
@SambitPrakash Have you linked your library and framework in Build Phases? Also you want to make sure you insert the appropriate code in the didFinishWithOptions

**Comment by nickjang1** [comment]
<img width="953" alt="screen shot 2017-08-16 at 2 38 41 pm" src="https://user-images.githubusercontent.com/25836904/29350329-b8b60b7a-8290-11e7-8c45-f9e5e288dd24.png">
include the libRNTwitterSignIn.a in Linked Frameworks and Libraries.
it isn't automatically included when execute command react-native link react-native-twitter-signin.

**Comment by SambitPrakash** [comment]
@HideyaSwider and @nickjang1  No luck for me. I have added linRNTwitterSignIn.a and Twitter.Framework in buildphase also. 

Additional Information : 
React native version : 0.47.1
react-native-twitter-signin : "^1.0.2"

**Comment by HideyaSwider** [comment]
@SambitPrakash you need to make sure you rebuild from XCode because it's a native module. I know this might be too obvious... But it could solve the problem.

**Comment by nickjang1** [comment]
Hi, @HideyaSwider.
Your guide works for me.
Thank you very much.

**Comment by SambitPrakash** [comment]
Finally i solved this issue. Thank you @HideyaSwider.
