### ISSUE TITLE
Failed to get request token in android

### ISSUE THREAD

**Issue by GrishmaM** [GoldenOwlAsia/react-native-twitter-signin#52]
i'm facing the below issue when i click on twitter-login button
**_com.twitter.sdk.android.core.TwitterAuthException: Failed to get request token_**
can some one help me in this, its bit urgent.

Thanks in advance

**Comment by senthilbalajiganesan** [comment]
+1, having same problem in lower version of android but works fine in Android 6 and 7

**Comment by ayushnawani** [comment]
@GrishmaM how did you resolved it ?

**Comment by rupalpatel0008** [comment]
@GrishmaM How did you solved it?

**Comment by lxcid** [comment]
Add `twittersdk://` to your callback URL. That works for me.

Saw the solution at https://stackoverflow.com/questions/33228235/failed-to-get-request-token-on-android-m-running-devices/50907791#50907791
