### ISSUE TITLE
createJSModules method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by alexisbg** [GoldenOwlAsia/react-native-twitter-signin#54]
Hi,

react-native: 0.47.2
react-native-twitter-signin: 1.0.2

There is an error while building:
```
:react-native-twitter-signin:compileReleaseJavaWithJavac ...node_modules\react-native-twitter-signin\
android\src\main\java\com\goldenowl\twittersignin\TwitterSigninPackage.java:28:
error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

It seems createJSModules @override is deprecated: [oblador/react-native-vector-icons#515](https://github.com/oblador/react-native-vector-icons/issues/515)

If it is commented, you can build again:
```
    //@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

**Comment by vijaya06** [comment]
same issue here!

**Comment by juanlet** [comment]
same issue here

**Comment by Johncy1997** [comment]
i am getting same error.Please anyone comment the solution

**Comment by juanlet** [comment]
Just delete the @Override on the  android\src\main\java\com\goldenowl\twittersignin\TwitterSigninPackage.java line 28
