### ISSUE TITLE
Undefined RNTwitterSignIn.init

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [GoldenOwlAsia/react-native-twitter-signin#56]
Hi i just wanna is how can i resolve this issue? 

I Got Error when i running the project..

![simulator screen shot - iphone 6 - 2017-09-21 at 11 11 35](https://user-images.githubusercontent.com/17594695/30677351-e247cfe8-9ebd-11e7-9f89-6118b8e91688.png)

Here may code:

```
function twitterPressHandler() {
  
  console.log('Twitter functions goes here!');

  RNTwitterSignIn.init(Constants.TWITTER_COMSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET);
  RNTwitterSignIn.logIn()
    .then((loginData)=>{
      console.log(loginData);
      const { authToken, authTokenSecret } = loginData;
      if (authToken && authTokenSecret) {
        this.setState({
          isLoggedIn: true,
        });
      }
    }).catch((error)=>{
      console.log(error);
    });

}
```

I hope i can get resolution on this issue thanks alot!

**Comment by Kottidev** [comment]
I have the same error

**Comment by nicoaureliovillanueva** [comment]
@Kottidev  i already found the solution

add this Link on your AppDelegate.m

`#import "RNTwitterSignIn.h"`

then add this framework to your Build Phases -> Link Binaries

`libRNTwitterSignIn.a`
`Twitter.framework`

**Comment by Zeroxys** [comment]
i hace the same error on android

**Comment by Zeroxys** [comment]
I have the same error on android

**Comment by Zeroxys** [comment]
for solve this problem on android only run react-native run-android

**Comment by gundam0910** [comment]
I have the same error, im using react-native as is.

**Comment by hophoppoppop** [comment]
@nicoaureliovillanueva 

I got some problem like this in IOS.

So i try your solution. When i try a touchableOpacity that have Twitter signin function it close the apps and show this error on xcode

`Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`

Do you got this problem when insert both libRNTwitterSignIn.a and Twitter.framework?

**Comment by thethanghn** [comment]
probably you linked them in a wrong way. Please try again as in guide.

**Comment by roulydev** [comment]
> @Kottidev i already found the solution
> 
> add this Link on your AppDelegate.m
> 
> `#import "RNTwitterSignIn.h"`
> 
> then add this framework to your Build Phases -> Link Binaries
> 
> `libRNTwitterSignIn.a`
> `Twitter.framework`

I have same error and when add `#import "RNTwitterSignIn.h"` it show error RNTwitterSignIn.h file not found.
I added RnTwitterSignIn.xcodeproj in Libararies folder and link in build phase ...
How I can fix it?
