### ISSUE TITLE
Error while signing in saved account in IOS

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [GoldenOwlAsia/react-native-twitter-signin#58]
Facing error. When twitter sign in uses saved account in ios settings. Please help. 

userInfo: 
   { NSLocalizedFailureReason: 'Twitter API error : Invalid or expired token. (code 89)',
     NSErrorFailingURLKey: null,
     NSLocalizedDescription: 'Request failed: unauthorized (401)',
     TWTRNetworkingStatusCode: 401 },
  domain: 'TwitterAPIErrorDomain' }

**Comment by thethanghn** [comment]
it is in the workflow, you need to check the error response and if the token expired, you need to log out the user so that they can sign in again.
