### ISSUE TITLE
How to access twitter rest API after login 

### ISSUE THREAD

**Issue by ratoncse24** [GoldenOwlAsia/react-native-twitter-signin#60]
Hello everyone
After login with twitter i need to access some twitter rest API using the logged user credentials  .

How can i perform on this ?

Thank you in advance

**Comment by rupalpatel0008** [comment]
I also have same question as @ratoncse24

**Comment by ahmermunaf** [comment]
same question

**Comment by thethanghn** [comment]
rest API is not in the scope of this library.
