### ISSUE TITLE
Twitter is not working in Android version 5.0.1

### ISSUE THREAD

**Issue by senthilbalajiganesan** [GoldenOwlAsia/react-native-twitter-signin#61]
Hey, I have been using this lib with Android version 7.0.0 and 6.0 which was really working fine, but when I tested the same app with Android version 5.0.1 it's not working out when I click on button it loads to twitter sign page (usually it does) and shows the twitter login in android version 6 and 7, but in android version 5 it automatically closes and doesn't show the login page. 
Can anyone please tell me, how to resolve this issue??pls,pls!!

**Comment by tirrorex** [comment]
What is your version of twitterKit and is the twitter app installed on device?

**Comment by thethanghn** [comment]
this one should be fixed

**Comment by mushinz** [comment]
I still get this on newer version :(
