### ISSUE TITLE
RNTwitterSignIn.init() falis silently

### ISSUE THREAD

**Issue by lorduriel** [GoldenOwlAsia/react-native-twitter-signin#62]
Using in iOS and RN 47.1 along with Facebook login
No error is thrown, but the promise of this function is never resolved.
What could cause that?

Here is my AppDelegate.m

```

 #import <TwitterKit/TwitterKit.h>
 #import <FBSDKCoreKit/FBSDKCoreKit.h>
 #import <FBSDKLoginKit/FBSDKLoginKit.h>
 #import "RNTwitterSignIn.h"
 
 #define TWITTER_SCHEME @"twitterkit-myKey"
 #define FACEBOOK_SCHEME  @"fbmyFbKey"
 
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
 {
   //more code
   [[Twitter sharedInstance] startWithConsumerKey:@"myKey" consumerSecret:@"mySecret"];
   [[FBSDKApplicationDelegate sharedInstance] application:application
                            didFinishLaunchingWithOptions:launchOptions];
  //more code
 }

 - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
 {
 
   return [[FBSDKApplicationDelegate sharedInstance] application:app
                                                         openURL:url
                                               sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                      annotation:options[UIApplicationOpenURLOptionsAnnotationKey]] ||
         [[Twitter sharedInstance] application:app openURL:url options:options];
   
 }
 

```

**Comment by lorduriel** [comment]
I just found out the cause and a possible a work-around. 
So... No error was thrown but the logIn never succesfully redirected me to my app as in a similar issue #55 
so i logged the value of the url that should match some one of the schemes i defined 

```
 #define TWITTER_SCHEME @"twitterkit-myTwitterKey"
 #define FACEBOOK_SCHEME  @"fbmyFacebookKey"
```


and i realized something, the original twitter key contains upper-case letters, but the url passed to the function is entirely lower-case , that way my condition to be redirected by twitter was never reached.

`twitterkit-myTwitterKey != twitterkit-mytwitterkey
`
To solve this, I simply defined a lower-case version of my key and got ready for that condition

```
if([ url scheme] isEqualToString:FACEBOOK_SCHEME){
   // return of facebook
}
if([ url scheme] isEqualToString:TWITTER_SCHEME){
   // return of twitter
}
if([ url scheme] isEqualToString:TWITTER_SCHEME_LOWER){
   // return of twitter
}
```
I don't know if this is well implemented but it works, twitter successfully redirects me now
Hope it helps

**Comment by zarcode** [comment]
@lorduriel can you be more specific where you added code, and what exactly code you added. I am stuck on this too, never get redirected back to app. I have my app key in Info.plist:
```    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-myTwitterKey </string>
      </array>
    </dict>```

**Comment by lorduriel** [comment]
Sure...
From the very beginning, i'm using twitter and fb so in the first `<dic>` element of your Info.plist add your urls and queries

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>twitterkit-myTwitterKey</string>
				<string>fbmyFacebookKey</string>
			</array>
		</dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>twitter</string>
		<string>twitterauth</string>
		<string>fbapi</string>
		... other fb queries
	</array>
```

those are al changes in your Info.plist.
Now in your Appdelagate.m provide your Twitter and FB or other instances under 
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
 
 // probably other providers
  [[Twitter sharedInstance] startWithConsumerKey:@"myTwitterKey" consumerSecret:@"myTwitterSecret"];
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];

// the default code
}
```

If you have reached this point with no problem and your app at least give you the chance to log in into your social network, your initial configuration and libraries are correctly configured.<br>
So as you say you authenticate successfully in your twitter but it never redirects you.
I loged the value of the url scheme received by the app and something weird happened (i'm not sure if this is normal) the url that was specified in the Info.plist `twitterkit-myTwitterKey` was transformed to lower-case `twitterkit-mytwitterkey` so the value never matched and redirection was never accomplished.<br>
So i defined 2 versions of the string in AppDelegate.m to verify them.
Just define the Strings and compare them inside 
`- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options`

```
//under twitter and facebook imports
#define TWITTER_SCHEME @"twitterkit-myTwitterKey"
//this one did the trick
#define TWITTER_SCHEME_LOWER @"twitterkit-mytwitterkey"
#define FACEBOOK_SCHEME  @"fbmyFacebookKey"

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
  
  if ([[url scheme] isEqualToString:FACEBOOK_SCHEME]){
    NSLog(@"redirect from facebook");
    return [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
  }
  if ([[url scheme] isEqualToString:TWITTER_SCHEME]){
    NSLog(@"This one doesn't work");
    return [[Twitter sharedInstance] application:app openURL:url options:options];
  }
  
  if ([[url scheme] isEqualToString:TWITTER_SCHEME_LOWER]){
    NSLog(@"This one is fine");
    return [[Twitter sharedInstance] application:app openURL:url options:options];
  }
 
  return NO;
 
}
```

And now you are ready to go... 
Howerver after you successfully log in with twitter it doesnt' return profile image or something else, just auth token and auth secret. There is were i am stuck, i don't understand how to use those tokens with my backend.

**Comment by zarcode** [comment]
Unfortunately still same for me. About getting profile details, after getting the access token you need to make a request for it to this endpoint https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show. Still haven't tried it, but I guess you can make HTTP request or use some of this js/node libs https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries. I'll be sending access token to the backend ( PHP ) that will take care of getting details.

**Comment by riftshock** [comment]
@lorduriel hey I followed your solution,
adding:

`[[Twitter sharedInstance] startWithConsumerKey:@"myTwitterKey" consumerSecret:@"myTwitterSecret"];`

throws me an error of:

`Thread 1: signal SIGABRT`

from:
```
int main(int argc, char * argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}
```

**Comment by juanlet** [comment]
I has a similar problem to you with url schemes....The solution in my case is that I had to unify duplicated keys on the info.plist since facebook and twitter they both have url schemes and you can't duplicate the entries, you have to put it all in the same array under one key and I also unified LSApplicationQueriesSchemes into one. So the two entries

```
<key>CFBundleURLTypes</key>
 <array>
   <dict>
     <key>CFBundleURLSchemes</key>
     <array>
       <string>twitterkit-XXXXXX</string>
       </array>
     </dict>
   </array>
 
   <key>CFBundleURLTypes</key>
   <array>
       <dict>
           <key>CFBundleURLSchemes</key>
           <array>
               <string>fbXXXX</string>
           </array>
       </dict>
   </array>
```

now in unified format would be:

```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-key</string>
        <string>fbkey</string>
        </array>
      </dict>
    </array>
  <key>LSApplicationQueriesSchemes</key>
    <array>
    <string>twitter</string>
    <string>twitterauth</string>
        <string>fbapi</string>
        <string>fb-messenger-share-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>
```

**Comment by alejandropablo** [comment]
> Sure...
> From the very beginning, i'm using twitter and fb so in the first `<dic>` element of your Info.plist add your urls and queries
> 
> ```
> 	<key>CFBundleURLTypes</key>
> 	<array>
> 		<dict>
> 			<key>CFBundleURLSchemes</key>
> 			<array>
> 				<string>twitterkit-myTwitterKey</string>
> 				<string>fbmyFacebookKey</string>
> 			</array>
> 		</dict>
> 	</array>
> 	<key>LSApplicationQueriesSchemes</key>
> 	<array>
> 		<string>twitter</string>
> 		<string>twitterauth</string>
> 		<string>fbapi</string>
> 		... other fb queries
> 	</array>
> ```
> 
> those are al changes in your Info.plist.
> Now in your Appdelagate.m provide your Twitter and FB or other instances under
> `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`
> 
> ```
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   NSURL *jsCodeLocation;
>  
>  // probably other providers
>   [[Twitter sharedInstance] startWithConsumerKey:@"myTwitterKey" consumerSecret:@"myTwitterSecret"];
>   [[FBSDKApplicationDelegate sharedInstance] application:application
>                            didFinishLaunchingWithOptions:launchOptions];
> 
> // the default code
> }
> ```
> 
> If you have reached this point with no problem and your app at least give you the chance to log in into your social network, your initial configuration and libraries are correctly configured.
> 
> So as you say you authenticate successfully in your twitter but it never redirects you.
> I loged the value of the url scheme received by the app and something weird happened (i'm not sure if this is normal) the url that was specified in the Info.plist `twitterkit-myTwitterKey` was transformed to lower-case `twitterkit-mytwitterkey` so the value never matched and redirection was never accomplished.
> 
> So i defined 2 versions of the string in AppDelegate.m to verify them.
> Just define the Strings and compare them inside
> `- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options`
> 
> ```
> //under twitter and facebook imports
> #define TWITTER_SCHEME @"twitterkit-myTwitterKey"
> //this one did the trick
> #define TWITTER_SCHEME_LOWER @"twitterkit-mytwitterkey"
> #define FACEBOOK_SCHEME  @"fbmyFacebookKey"
> 
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
> {
>   
>   if ([[url scheme] isEqualToString:FACEBOOK_SCHEME]){
>     NSLog(@"redirect from facebook");
>     return [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
>   }
>   if ([[url scheme] isEqualToString:TWITTER_SCHEME]){
>     NSLog(@"This one doesn't work");
>     return [[Twitter sharedInstance] application:app openURL:url options:options];
>   }
>   
>   if ([[url scheme] isEqualToString:TWITTER_SCHEME_LOWER]){
>     NSLog(@"This one is fine");
>     return [[Twitter sharedInstance] application:app openURL:url options:options];
>   }
>  
>   return NO;
>  
> }
> ```
> 
> And now you are ready to go...
> Howerver after you successfully log in with twitter it doesnt' return profile image or something else, just auth token and auth secret. There is were i am stuck, i don't understand how to use those tokens with my backend.

Been stuck with this for 2 days. You just saved me. Thanks.

RN 60.x
TW 3.4.x

**Comment by taj567** [comment]
[Error: Twitter signin error] in react native IOS

https://stackoverflow.com/questions/60648762/exception-when-initializing-react-native-twitter-signin/78378122#78378122

**Comment by taj567** [comment]
[Error: Twitter signin error] in react native IOS #129

https://github.com/IMusicTeam/iMusic/issues/129
