### ISSUE TITLE
Requires TwitterKit 3.1.0 on android if twitter app is not installed

### ISSUE THREAD

**Issue by tirrorex** [GoldenOwlAsia/react-native-twitter-signin#64]
Please update the documentation.
This framework will not work on android with twitterKit < 3.1.0 if twitter app is not installed on device.
This is due to a known issue in twitterKit.
TwitterKit will return the error USER_CANCELLED.
Ref : https://twittercommunity.com/t/bug-twitter-kit-ios-3-0-4-login-without-twitter-app-installed-fails-to-call-completion-when-no-network-connection/90141/6

**Comment by thethanghn** [comment]
fixed
