### ISSUE TITLE
 RNTwitterSignIn.init() does not work on IOS

### ISSUE THREAD

**Issue by deejaygeroso** [GoldenOwlAsia/react-native-twitter-signin#68]
xcode version 9.1
react-native version 50.4
react-native-twitter-signing version 1.0.2

 RNTwitterSignIn.init() error

I don't really understand the error but under debug navigator it shows this:
`#0  facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) at <project-location>/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:114`

it says:
`Thread 1: EXC_BREAKPOINT (code=1, subcode=0x102aa7c34)`

**Comment by gvillenave** [comment]
I'm seeing the same error, any ideas?

**Comment by riftshock** [comment]
sorry man, still have no clue how to solve this..

**Comment by juanlet** [comment]
I have the same problem. I can use init in android but not on ios

**Comment by thethanghn** [comment]
fixed
