### ISSUE TITLE
How can I get follower after logged in ?

### ISSUE THREAD

**Issue by waleedarshad-vf** [GoldenOwlAsia/react-native-twitter-signin#7]

**Comment by tarkanlar** [comment]
Hi @waleedarshad-vf could you find a solution for this?

**Comment by waleedarshad-vf** [comment]
yep. i hit manually to the api mentions in twitter docs. Currently there is no way current library provides to get follower according to me

https://dev.twitter.com/rest/reference/get/followers/ids

**Comment by salimbutex** [comment]
@waleedarshad-vf 
I need same features.... can u pls give me some ideas pls

**Comment by waleedarshad-vf** [comment]
https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids

**Comment by waleedarshad-vf** [comment]
hit to twitter api directly

**Comment by salimbutex** [comment]
what do u mean by hit hit man?
I saw their api, but does not merge with this libray... 
sry I am new to android... Not sure how to work with their api in android...
