### ISSUE TITLE
Unable to logut folowing example code

### ISSUE THREAD

**Issue by punksta** [GoldenOwlAsia/react-native-twitter-signin#71]
if I try to logout in next session after log in I get this:
```
Must initialize Twitter before using getInstance()
checkInitialized
    Twitter.java:143
getInstance
    Twitter.java:151
getInstance
    TwitterCore.java:88
logOut
    TwitterSigninModule.java:97
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818
```
We should call `init` before logout perhaps

reproduce:
- open app
- log in via twitter
- close(kill) app
- open app
- try to log out

**Comment by thethanghn** [comment]
please follow Example.

**Comment by punksta** [comment]
Hi. Did you read the testcase? 
You don't call "init" in logout method here.
https://github.com/GoldenOwlAsia/react-native-twitter-signin/blob/master/Example/TwitterButton.js#L43
if you call logout in next app launch after login, the example does not work.
