### ISSUE TITLE
cannot read 'init' property of undefined

### ISSUE THREAD

**Issue by KrishnaChittodia21** [GoldenOwlAsia/react-native-twitter-signin#73]
> 
Please help me remove this error i am not able to figure out,I am running my app on android device
> ![screenshot_2018-02-01-06-13-05](https://user-images.githubusercontent.com/23017491/35679119-eb00c47e-077b-11e8-954f-0355c9205f13.png)

**Comment by Alwayswannasad** [comment]
Have the same error, could someone help how to resolve this issue?

**Comment by JackkFi5h** [comment]
Also having this issue, how do I resolve?
