### ISSUE TITLE
Solution to Twitter Sign In not working on 51+, Linking didn't work

### ISSUE THREAD

**Issue by coryMcan** [GoldenOwlAsia/react-native-twitter-signin#77]
Hi all,
After many hours of trying the install steps listed here, we dove into the native code and realized that the current version of react-native-twitter-signin isn't up to date with the current Twitter API changes.

In TwitterSignin.m, we updated the NSURLRequest for verifyCredentials.
In this example we replaced 

Original:
```
      TWTRAPIClient *client = [TWTRAPIClient clientWithCurrentUser];
      NSURLRequest *request = [client URLRequestWithMethod:@"GET"
                                                       URL:@"https://api.twitter.com/1.1/account/verify_credentials.json"
                                                parameters:@{@"include_email": @"true", @"skip_status": @"true"}
                                                     error:nil];
```

Updated:
```
  TWTRAPIClient *client = [TWTRAPIClient clientWithCurrentUser];
      NSString *verifyCredentialsEndpoint = @"https://api.twitter.com/1.1/account/verify_credentials.json";
      NSDictionary *params = @{@"include_email": @"true", @"skip_status": @"true"};
      NSError *clientError;
      NSURLRequest *request = [client URLRequestWithMethod:@"GET" URLString:verifyCredentialsEndpoint
                                          parameters:params error:&clientError];
```

You can see that we updated URL with URLString.

On line 9, also replace the TwitterKit.h import with

```
@import TwitterKit;
```

Hope this helps someone!

**Comment by hophoppoppop** [comment]
@coryMcan I try to change URL to URLString in RNTwitterSignIn it show an error:
`No visible @interface for 'TWTRAPIClient' declares the selector URLRequestWithMethod:URLString:parameters:error:'`

**Comment by thethanghn** [comment]
this should be fixed by now

**Comment by kostya9116** [comment]
No, it isn't fixed

**Comment by kostya9116** [comment]
![image](https://user-images.githubusercontent.com/20957047/53699411-5f85bb80-3e01-11e9-9a3b-0566cbfde6ec.png)
