### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0) when try RNTwitterSignIn.logIn()

### ISSUE THREAD

**Issue by hophoppoppop** [GoldenOwlAsia/react-native-twitter-signin#78]
So this plugin is working well on android. but when i try it on IOS it always show this error on xcode "Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)" everytime i press button that has RNTwitterSignIn.logIn() on it

**Comment by mastersam92** [comment]
I've got some error when add data to `Info.plist`.. add **incorrect**.
Check data, that you added.

In my case, it was like this:
(incorrect): `<string>twitterkit- LongConsumerKey</string>`
(correct):    `<string>twitterkit-LongConsumerKey</string>`

As you can see, one extra space( in my case ) before LongConsumerKey - and, "EXC_BAD_INSTRUCTION..."
