### ISSUE TITLE
On Press cancel, app just get crashed instead of getting back to app

### ISSUE THREAD

**Issue by waleedarshad-vf** [GoldenOwlAsia/react-native-twitter-signin#8]

**Comment by waleedarshad-vf** [comment]
@GoldenowlConsultingCompany ?

**Comment by waleedarshad-vf** [comment]
Anybody Would like to answer? i am stuck with my application. would you please? how can i tackle this problem. please

**Comment by RakanNimer** [comment]
You can use my fork : https://github.com/RakanNimer/react-native-twitter-signin/

But it uses promises not callback, check out the readme

**Comment by RakanNimer** [comment]
npm install --save RakanNimer/react-native-twitter-signin. 
Using it in prod so you don't have to worry much about unannounced breaking changes.

**Comment by jitu9717** [comment]
@RakanNimer : I am  getting this error version 0.31.0
/home/ttnd/projects/rally-bus/node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin/TwitterSigninModule.java:32: error: TwitterSigninModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener
public class TwitterSigninModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
1 error
:react-native-twitter-signin:compileReleaseJavaWithJavac FAILED

**Comment by RakanNimer** [comment]
Which package are you using ?

**Comment by jitu9717** [comment]
@RakanNimer : react-native-twitter-signin , my react-native version is 0.31.0

**Comment by jitu9717** [comment]
I resolved this by adding in file /node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin/TwitterSigninModule.java

public void onNewIntent(Intent intent) {
}

but now app crashes on clicking twitter icon

**Comment by RakanNimer** [comment]
Try out my fork https://github.com/RakanNimer/react-native-twitter-signin/

But it uses promises not callback, check out the readme

**Comment by jitu9717** [comment]
Hey @RakanNimer : still getting the same error 

/home/ttnd/projects/rally-bus/node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin/TwitterSigninModule.java:35: error: TwitterSigninModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class TwitterSigninModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/home/ttnd/projects/rally-bus/node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin/TwitterSigninModule.java:93: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-twitter-signin:compileReleaseJavaWithJavac FAILED

**Comment by jitu9717** [comment]
can  you share the working code for twitter login on react native

**Comment by RakanNimer** [comment]
Oh you're getting this error because you're on react-native 0.31. In 0.33 onActivityResult now needs Activity. So either update to RN0.33+ or fork and  remove 
```Activity currentActivity ```
 from 
 ```    
 public void onActivityResult(Activity currentActivity, int requestCode, int resultCode, Intent data) {
 ```

**Comment by ignivarahulsaini** [comment]
_twitterSignIn() {
              TwitterSignin.init(Constants.TWITTER_COMSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET).then(() => {
               return TwitterSignin.logIn();
              })
              .then((loginData)=>{
                Alert.alert('Success', JSON.stringify(loginData));
              }).catch((error)=>{
                Alert.alert('Error', JSON.stringify(error));
              });
          }

But I am not getting loginData after successfully loggedIn @RakanNimer

**Comment by ignivarahulsaini** [comment]
And I also replaced Constants.TWITTER_COMSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET with real ones :)

**Comment by imbudhiraja** [comment]
@RakanNimer https://github.com/RakanNimer/react-native-twitter-signin/ it fixes the cancel crash but when we authrozired the app it wont return any data.

**Comment by RakanNimer** [comment]
Hey could you please open an issue on the concerned repo with a minimal
repro of the error? Also don't forget that the native calls returns a
promise in my version.

**Comment by AmitPandya007** [comment]
@rakannimer How can I get  user email and user_birthday details?
