### ISSUE TITLE
Unable to retrieve login infos - Not receiving response

### ISSUE THREAD

**Issue by greeeg** [GoldenOwlAsia/react-native-twitter-signin#81]
After one login with this package, I'm unable to logout or to login one more time : the promise is not resolved or catched. Any information about this kind of bug?

`React Native 0.54.2`
`React 16.3.0-alpha.1`

**Comment by Nahani** [comment]
I have the same issue.The "then()" is never called...

**Comment by lavilanativapps** [comment]
Was this problem solved?
