### ISSUE TITLE
attempt made to log in or like a tweet without a valid twitter kit url scheme

### ISSUE THREAD

**Issue by hoanghapo** [GoldenOwlAsia/react-native-twitter-signin#84]

**Comment by bintoll** [comment]
Hello, I have the same issue, did you resolve it somehow?

**Comment by juanlet** [comment]
I fixed it....The solution in my case is that I had to unify duplicated keys on the info.plist since facebook and twitter they both have url schemes and you can't duplicate the entries, you have to put it all in the same array under one key and I also unified LSApplicationQueriesSchemes into one. So the two entries 

 ```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-XXXXXX</string>
        </array>
      </dict>
    </array>
  
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>fbXXXX</string>
            </array>
        </dict>
    </array>

```
now in unified format would be:



```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-key</string>
        <string>fbkey</string>
        </array>
      </dict>
    </array>
  <key>LSApplicationQueriesSchemes</key>
    <array>
    <string>twitter</string>
    <string>twitterauth</string>
        <string>fbapi</string>
        <string>fb-messenger-share-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>
```

**Comment by rohitiglas** [comment]
<img width="417" alt="Screenshot 2022-01-31 at 1 33 39 PM" src="https://user-images.githubusercontent.com/17780617/151818641-ac1fee9c-ad22-4373-8984-5ecc25c2b68f.png">


**Step1:** #import <TwitterKit/TWTRKit.h>

**Step2:** 
Added the consumerKey and consumerSecret in 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
// Add this line 
**[[Twitter sharedInstance] startWithConsumerKey:@"Key" consumerSecret:@"SecretKey"];**

}

**Step:3**

**- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options 
{**

// **Add this line**
            
            if ([[url scheme] hasPrefix:@"twitter"] == YES) {
    return [[Twitter sharedInstance] application:application openURL:url options:options];
    }


            **}**

**Comment by Saad9624** [comment]
Unable to resolve it.
Tried everything.
