### ISSUE TITLE
TwitterSignin is not loaded thru NativeModules

### ISSUE THREAD

**Issue by hepu** [GoldenOwlAsia/react-native-twitter-signin#9]
Gives error trying to call LogIn method that documentation says

**Comment by nayelymartinez** [comment]
Make sure that your React corresponds to the correct 'react-native' import. We renamed ours to ReactNative and then did:

    var { NativeModules} = ReactNative;

**Comment by hamism** [comment]
@nayelymartinez  can elaborate on your solution or give us a snippet of code.
