### ISSUE TITLE
Error in ios, works in android: Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_Twitter", referenced from:       objc-class-ref in libRNTwitterSignIn.a(RNTwitterSignIn.o)

### ISSUE THREAD

**Issue by juanlet** [GoldenOwlAsia/react-native-twitter-signin#90]
I followed the instructions exactly but I'm getting the error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Twitter", referenced from:
      objc-class-ref in libRNTwitterSignIn.a(RNTwitterSignIn.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?. Thank you very much

**Comment by juanlet** [comment]
I added the twitterKit files again but now I'm getting a red screet at the execution of Login method.....

<img width="339" alt="screen shot 2018-04-22 at 13 07 42" src="https://user-images.githubusercontent.com/12257699/39097109-2e802aaa-462e-11e8-93c5-1f523ea4b888.png">

**Comment by juanlet** [comment]
https://twittercommunity.com/t/twitterkit-v3-causes-exception-upon-sign-in-on-ios/88143

**Comment by juanlet** [comment]
I fixed it....The solution in my case to the second problem that I mention on the comments to Pritish Vaidya of twitter complaining about me trying to login wihtout a URL scheme was that I had to unify duplicated keys on the info.plist since facebook and twitter they both have url schemes and you can't duplicate the entries, you have to put it all in the same array under one key and I also unified LSApplicationQueriesSchemes into one. As you can see in the plist above is duplicated for both entries. So the two entries now in unified format would be:

```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-key</string>
        <string>fbkey</string>
        </array>
      </dict>
    </array>
  <key>LSApplicationQueriesSchemes</key>
    <array>
    <string>twitter</string>
    <string>twitterauth</string>
        <string>fbapi</string>
        <string>fb-messenger-share-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>
```

**Comment by SonamKamble** [comment]
Getting the same error in iOS.
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Twitter", referenced from:
      objc-class-ref in libRNTwitterSignIn.a(RNTwitterSignIn.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Kindly suggest the solution.

**Comment by linh232323** [comment]
I get the same error. Does any one know how to fix ?

```
Undefined symbols for architecture x86_64:
"OBJC_CLASS$_Twitter", referenced from:
objc-class-ref in libRNTwitterSignIn.a(RNTwitterSignIn.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by linh232323** [comment]
Hi, just found solution now. Because TwitterKit has already upgraded and use different name.
Then i have to"
1. Add TwitterKit to Linked Frameworkd & Libraries
2. Adjust #import <TwitterKit/TWTRKit.h>

Because GoldenOwlAsia doesn't update new code, so that i forked here https://github.com/linh232323/react-native-twitter-signin/blob/master/ios/RNTwitterSignIn.m

**Comment by webmasterdragon** [comment]
It didn't fixed for me.
Any solutions?

**Comment by punksta** [comment]
Still having this issue.

react-native 0.59.10
everything is linked via cocoapods

```
 pod 'TwitterKit', '~> 3.3.0'
 pod "react-native-twitter-signin", path: "../node_modules/react-native-twitter-signin"
```

**Comment by abdi4** [comment]
@punksta hello mate, did you manage to find a solution as i’m having the same problem?
