### ISSUE TITLE
Is GoldenOwlAsia Active? We need to update this to the new gradle to use implementation instead of compile

### ISSUE THREAD

**Issue by juanlet** [GoldenOwlAsia/react-native-twitter-signin#93]
This library needs to be updated to adjust to the new gradle since it throws warnings. Is there any chance that GoldenOwlAsia is still active? It would be a shame to abandon such a good library like this, unique in its functionality, there is no other react native option to sign in to twitter, at least not as good as this one. I'm talking about this kind of difference  https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle to avoid warnings like this  Configuration 'compile' in project ':react-native-twitter-signin' is deprecated. Use 'implementation' instead. Maybe I'm missing something but I wanted to brought it up.

**Comment by thethanghn** [comment]
I am not frequently checking this due to busy day job, what are the warnings you got? can you provide screenshots?

**Comment by juanlet** [comment]
I just get warnings "Configuration 'compile' in project ':react-native-twitter-signin' is deprecated. Use 'implementation' instead. " ....I think the new gradle is asking to change that to comply with the implementation statement in the gradle file instead of using compile. Could you check that once you have 5 minutes? There is an error as well that I have to change manually everytime i install a project in a new machine, in the file TwitterSigninPackage I have to remove manually the @override from the top of createJSModules() method, the error with gradle 3.0.1 is that is not overriding method from parent. Could you remove that override from the method and release a new version so we can have that without having to edit the file everytime? If you need further details I can provide them to you, I want this package to keep on going since it's excellent and unique

**Comment by juanlet** [comment]
@thethanghn please, accept that pull request to remove the breaking line "override", there are a lot of people having this problem when they pull a project that contain this library, this would fix that https://github.com/GoldenOwlAsia/react-native-twitter-signin/pull/97

**Comment by thethanghn** [comment]
fixed
