### ISSUE TITLE
WARNING - ios;  to avoid errors with redirections after login, for anyone reading this don't duplicate keys  CFBundleURLSchemes  and LSApplicationQueriesSchemes in info.plist if you are using twitter along with facebook/Google/etc providers

### ISSUE THREAD

**Issue by juanlet** [GoldenOwlAsia/react-native-twitter-signin#94]
A common mistake is to duplicate  CFBundleURLSchemes  keys if you have multiple providers that need redirection after login. Imagine you had facebook and twitter as auth providers, and you need to redirect to the app after login with either of them. A wrong way of adding multiple providers to info.plist file in ios project would be:

```
<key>CFBundleURLTypes</key>
 <array>
   <dict>
     <key>CFBundleURLSchemes</key>
     <array>
       <string>twitterkit-XXXXXX</string>
       </array>
     </dict>
   </array>
 
   <key>CFBundleURLTypes</key>
   <array>
       <dict>
           <key>CFBundleURLSchemes</key>
           <array>
               <string>fbXXXX</string>
           </array>
       </dict>
   </array>


```

The correct way is to unify strings in an array under the same key, it applies for any key in fact, CFBundleURLTypes  for example:

```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>twitterkit-key</string>
        <string>fbkey</string>
        </array>
      </dict>
    </array>

```
For LSApplicationQueriesSchemes key for example the unified version would be
 ```
<key>LSApplicationQueriesSchemes</key>
    <array>
    <string>twitter</string>
    <string>twitterauth</string>
        <string>fbapi</string>
        <string>fb-messenger-share-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>

```
instead of declaring it multiple times for each provider which would be an error.

We should update the docs warning about this since I've seen is a common mistake that prevents the user from being redirected after login. Also if you are using firebase authentication module make sure bundle id for ios matches the one in your project settings in xcode(you will first need to add an ios app in Firebase console and set it with the correct bundle id of course)

**Comment by jslz** [comment]
For us, the exact opposite is true. $0.02.

**Comment by thethanghn** [comment]
hmm, I doubt it, because URLSchemes in Info.plist is a quick way to change thing.
